// packages/create-fhevm-dapp/templates/vue/src/App.vue
<script setup lang="ts">
import Header from './components/Header.vue';
import EncryptedCounter from './components/EncryptedCounter.vue';
</script>

<template>
  <div id="app">
    <Header />
    <main>
      <EncryptedCounter />
    </main>
    <footer class="footer">
      <div class="container">
        <p>
          Built with
          <a href="https://vuejs.org" target="_blank" rel="noopener">Vue 3</a>
          +
          <a href="https://github.com/zama-ai/fhevm" target="_blank" rel="noopener">FHEVM</a>
        </p>
        <p class="links">
          <a href="https://github.com/zama-ai/fhevm-hardhat-template" target="_blank" rel="noopener">
            📚 Docs
          </a>
          <span>•</span>
          <a href="https://github.com/zama-ai" target="_blank" rel="noopener">
            🔧 GitHub
          </a>
        </p>
      </div>
    </footer>
  </div>
</template>

<style scoped>
#app {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

main {
  flex: 1;
  padding: 2rem 0;
}

.footer {
  border-top: 1px solid #ffffff20;
  padding: 2rem 0;
  margin-top: 4rem;
  text-align: center;
}

.footer .container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem;
}

.footer p {
  margin: 0.5rem 0;
  opacity: 0.7;
}

.footer a {
  color: #42b883;
  text-decoration: none;
  font-weight: 500;
}

.footer a:hover {
  text-decoration: underline;
}

.footer .links {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
}

.footer .links span {
  opacity: 0.5;
}
</style>

// packages/create-fhevm-dapp/templates/nextjs/app/page.tsx
import { EncryptedCounter } from "~/components/EncryptedCounter";

export default function Home() {
  return (
    <main className="min-h-screen bg-base-200 py-12 px-4">
      <div className="container mx-auto max-w-4xl">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">
            🔐 FHEVM SDK Example
          </h1>
          <p className="text-xl text-base-content/70 mb-2">
            Built with <code className="badge badge-primary badge-lg">@fhevm/react</code>
          </p>
          <p className="text-lg text-base-content/60">
            Wagmi-like hooks for Fully Homomorphic Encryption on Ethereum
          </p>
        </div>

        {/* Demo Component */}
        <EncryptedCounter />

        {/* Info Footer */}
        <div className="mt-12 text-center text-sm text-base-content/50">
          <p>
            Learn more about FHEVM at{" "}
            <a
              href="https://docs.zama.ai/fhevm"
              target="_blank"
              rel="noopener noreferrer"
              className="link link-primary"
            >
              docs.zama.ai
            </a>
          </p>
        </div>
      </div>
    </main>
  );
}
